// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.75.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Representation.System.Test
{
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;
    
    using global::OBeautifulCode.Assertion.Recipes;

    using global::Xunit;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.75.0")]
    public static partial class RepresentationSystemDummyFactoryTest
    {
        [Fact]
        public static void RepresentationSystemDummyFactory___Should_derive_from_DefaultRepresentationSystemDummyFactory___When_reflecting()
        {
            // Arrange
            var dummyFactoryType = typeof(RepresentationSystemDummyFactory);

            var defaultDummyFactoryType = typeof(DefaultRepresentationSystemDummyFactory);

            // Act, Assert
            defaultDummyFactoryType.GetInterface(nameof(IDummyFactory)).AsTest().Must().NotBeNull();

            dummyFactoryType.BaseType.AsTest().Must().BeEqualTo(defaultDummyFactoryType);
        }
    }
}